In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [2]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
ds = fetch_california_housing()
x_train, x_test, y_train, y_test = train_test_split(ds['data'], ds['target'], test_size = 0.8)
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

<h3>Testing linear regression without regularization</h3>

In [3]:
from sklearn.linear_model import LinearRegression as SKLR
from models.regression import LinearRegression
sk_lr = SKLR()
sk_lr = sk_lr.fit(x_train, y_train)

In [4]:
sk_lr.coef_

array([ 0.84556901,  0.10953572, -0.32282234,  0.36140828,  0.00417713,
       -0.05263559, -0.87787348, -0.87102591])

In [5]:
sk_lr.intercept_

np.float64(2.066029021317892)

In [6]:
test_lr = LinearRegression()
test_lr.fit(x_train, y_train, 0.0001)

In [7]:
test_lr.coefficents

array([ 0.84556901,  0.10953572, -0.32282234,  0.36140829,  0.00417713,
       -0.05263559, -0.87787348, -0.87102591])

In [8]:
test_lr.intercept

np.float64(2.0660290213072585)

In [9]:
print(mean_squared_error(y_test, sk_lr.predict(x_test)))
print(r2_score(y_test, sk_lr.predict(x_test)))

0.5248026848182101
0.60686448958553


In [10]:
print(mean_squared_error(y_test, test_lr.predict(x_test)))
print(r2_score(y_test, test_lr.predict(x_test)))

0.5248026848665217
0.6068644895493391


<h3>Testing lasso</h3>

In [11]:
from models.regression import Lasso
from sklearn.linear_model import Lasso as SKLasso

In [12]:
test_lasso = Lasso(0.1)

In [13]:
test_lasso.fit(x_train, y_train, 0.01)

In [14]:
test_lasso.coefficents

array([ 0.69470665,  0.09952343, -0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.        ])

In [15]:
test_lasso.intercept

np.float64(2.0659398282677954)

In [17]:
sklasso = SKLasso(0.1)

In [18]:
sklasso = sklasso.fit(x_train, y_train)

In [19]:
sklasso.coef_

array([ 0.69476322,  0.09957099, -0.        , -0.        ,  0.        ,
       -0.        , -0.        , -0.        ])

In [20]:
sklasso.intercept_

np.float64(2.0660290213178314)

In [21]:
print(mean_squared_error(y_test, test_lasso.predict(x_test)))
r2_score(y_test, test_lasso.predict(x_test))

0.6797952866283414


0.4907578129510539

In [22]:
print(mean_squared_error(y_test, sklasso.predict(x_test)))
r2_score(y_test, sklasso.predict(x_test))

0.6797717255607415


0.4907754628080474

<h3>Testing ridge</h3>

In [3]:
from sklearn.linear_model import Ridge as SKRidge
from models.regression import Ridge

In [14]:
test_ridge = Ridge(0.01)
test_ridge.fit(x_train, y_train, 0.0001)

In [15]:
test_ridge.coefficents

array([ 0.84271363,  0.13605618, -0.2412151 ,  0.25410362, -0.00243057,
       -0.03204032, -0.8712751 , -0.84051319])

In [16]:
test_ridge.intercept

np.float64(2.0726926088627806)

In [17]:
skr = SKRidge(0.01)

In [18]:
skr = skr.fit(x_test, y_test)

In [19]:
skr.coef_

array([ 0.8271207 ,  0.11415841, -0.27345538,  0.31925564, -0.00517604,
       -0.04111943, -0.905499  , -0.87674945])

In [11]:
skr.intercept_

np.float64(2.0675245591085334)

In [12]:
print(mean_squared_error(y_test, test_ridge.predict(x_test)))
r2_score(y_test, test_ridge.predict(x_test))

0.5274830197060321


0.6026596470503957

In [13]:
print(mean_squared_error(y_test, skr.predict(x_test)))
r2_score(y_test, skr.predict(x_test))

0.5248537999076959


0.6046401754913588

<h3>Testing elastic net</h3>

In [ ]:
from sklearn.linear_model import ElasticNet as SKEN
from models import ElasticNet

In [ ]:
test_en = ElasticNet(0.1, 0.1)
test_en.fit(x_test, y_test, 0.01)

In [ ]:
test_en.a

array([ 0.75821246,  0.14913039, -0.0709343 ,  0.08200048,  0.00089227,
       -0.02398056, -0.49189524, -0.45321651])

In [ ]:
test_en.intercept

[np.float64(2.0718987227774655)]

In [ ]:
sken = SKEN()
sken = sken.fit(x_test, y_test)

In [ ]:
sken.coef_

array([ 0.19568557,  0.        ,  0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        ])

In [ ]:
sken.intercept_

np.float64(2.0718987227470946)

In [ ]:
print(mean_squared_error(y_test, test_en.predict(x_test)))
r2_score(y_test, test_en.predict(x_test))

0.6106808115672934


0.5442724932011275

In [ ]:
print(mean_squared_error(y_test, sken.predict(x_test)))
r2_score(y_test, sken.predict(x_test))

1.067741812780713


0.20318551847957877